# ---- Site basics ----
title: BitSheepp
description: My site
url: https://bitsheepp.github.io
baseurl: ""   # 根目录发布，请保持空字符串

# 主题（GitHub Pages 官方主题）
theme: jekyll-theme-primer

# ---- Markdown ----
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# ---- 不启用任何自定义插件（github-pages 会自动加载它自己的白名单插件） ----
# plugins:  # 不写！让 github-pages 自己管理

# ---- 仅包含简单页面目录 ----
include:
  - _pages

# ---- 显式排除不需要参与构建的文件/目录 ----
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - bin/
  - Dockerfile
  - docker-compose.yml
  - docker-compose-slim.yml
  - readme_preview/
  - lighthouse_results/
  - _pages/about_einstein.md

# 不保留任何自定义集合（books/news/projects 全移除）
# collections:  # 不写

# 让 feed/sitemap 使用内置（无需显式配置）
